///////////////////////////////////////////////////////////
//  Patente.cs
//  Implementation of the Class Patente
//  Generated by Enterprise Architect
//  Created on:      05-may.-2022 21:16:55
//  Original author: gasto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Services.DomainModel.Security.Composite {
	/// <summary>
	/// This class (a) represents leaf objects in the composition, and (b) defines
	/// behaviour for primitive objects in the composition.
	/// </summary>
	public class Patente : Component {

		public string FormName { get; set; }

		public string MenuItemName { get; set; }

        public override void Add(Component component)
        {
            throw new Exception("No se pueden agregar elementos sobre primitivos");
        }

        public override int ChildrenCount()
        {
            return 0;
        }

        public override void Remove(Component component)
        {
            throw new Exception("No se pueden quitar elementos sobre primitivos");
        }
    }//end Patente

}//end namespace Composite